### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by adawg123** [tensult/aws-automation#22]
When running the lambda:
const AWS = require('aws-sdk');
const cloudwatchLogs = new AWS.CloudWatchLogs();
//const requestParameters = false;

function setRetentionOfCloudwatchLogGroup(logGroupName, duration) {
    let params = {
        logGroupName : logGroupName,
        retentionInDays: duration
    };
    return cloudwatchLogs.putRetentionPolicy(params).promise();
}

exports.handler = async (event) => {
    const logGroupName = event.logGroupName ? event.logGroupName : event.detail.requestParameters.logGroupName;
    try {
        await setRetentionOfCloudwatchLogGroup(logGroupName, 14);
        console.log('Retention has been set to ' + logGroupName + 'for 2 weeks');
        return;
    } catch(error) {
        console.error(error);
        throw error;
    }
};

Getting following error:

Response:
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'requestParameters' of undefined",
  "trace": [
    "TypeError: Cannot read property 'requestParameters' of undefined",
    "    at Runtime.exports.handler (/var/task/index.js:14:81)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)",
    "    at process._tickCallback (internal/process/next_tick.js:68:7)"
  ]
}

Request ID:
"aab21312-d1f8-4940-a9ac-2dab49dd858e"

Function Logs:
START RequestId: aab21312-d1f8-4940-a9ac-2dab49dd858e Version: $LATEST
2019-07-17T14:28:30.805Z	aab21312-d1f8-4940-a9ac-2dab49dd858e	ERROR	Invoke Error	{"errorType":"TypeError","errorMessage":"Cannot read property 'requestParameters' of undefined","stack":["TypeError: Cannot read property 'requestParameters' of undefined","    at Runtime.exports.handler (/var/task/index.js:14:81)","    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
END RequestId: aab21312-d1f8-4940-a9ac-2dab49dd858e
REPORT RequestId: aab21312-d1f8-4940-a9ac-2dab49dd858e	Duration: 21.63 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 78 MB

**Comment by adawg123** [comment]
Could you please look at this ASAP. Thank you.

**Comment by koladilip** [comment]
Can you add following line to Lambda handler function at the starting and provide output here:
console.log(JSON.stringify(event));

Also how are you triggering this Lambda function

Thanks,
Dilip
Tensult
________________________________

**Comment by adawg123** [comment]
Hi, thanks for getting back. I put the line before the handler and it gave event is not defined error. I also put it after the handler which is commented but I got the same error originally. I am triggering this lambda through cloudwatch rule when a new log group is created to set log retention to 14 days as described here: https://medium.com/tensult/manage-aws-cloudwatch-log-group-retention-using-automation-26add478b0c5. Please let me know a solution asap. 

const AWS = require('aws-sdk');
const cloudwatchLogs = new AWS.CloudWatchLogs();

function setRetentionOfCloudwatchLogGroup(logGroupName, duration) {
    let params = {
        logGroupName : logGroupName,
        retentionInDays: duration
    };
    return cloudwatchLogs.putRetentionPolicy(params).promise();
}

console.log(JSON.stringify(event)); 
exports.handler = async (event) => { 
    //console.log(JSON.stringify(event)); 
    const logGroupName = event.logGroupName ? event.logGroupName : event.detail.requestParameters.logGroupName;
    try {
        await setRetentionOfCloudwatchLogGroup(logGroupName, 14);
        console.log('Retention has been set to ' + logGroupName + 'for 2 weeks');
        return;
    } catch(error) {
        console.error(error);
        throw error;
    }
};


Error:
Response:
{
  "errorMessage": "event is not defined",
  "errorType": "ReferenceError",
  "stackTrace": [
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}

Request ID:
"06b083b8-912b-412d-80ef-04c36c1ec588"

Function Logs:
START RequestId: 06b083b8-912b-412d-80ef-04c36c1ec588 Version: $LATEST
module initialization error: ReferenceError
    at Object.<anonymous> (/var/task/index.js:12:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: 06b083b8-912b-412d-80ef-04c36c1ec588
REPORT RequestId: 06b083b8-912b-412d-80ef-04c36c1ec588	Duration: 91.97 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 27 MB	
module initialization error
ReferenceError

**Comment by koladilip** [comment]
console.log(JSON.stringify(event)); // <-- not here
exports.handler = async (event) => {
console.log(JSON.stringify(event)); // <-- should be here

You need to add inside the function.

**Comment by adawg123** [comment]
ok, I did that too but I get the original error in this case

const AWS = require('aws-sdk');
const cloudwatchLogs = new AWS.CloudWatchLogs();

function setRetentionOfCloudwatchLogGroup(logGroupName, duration) {
    let params = {
        logGroupName : logGroupName,
        retentionInDays: duration
    };
    return cloudwatchLogs.putRetentionPolicy(params).promise();
}

exports.handler = async (event) => { 
    console.log(JSON.stringify(event)); 
    const logGroupName = event.logGroupName ? event.logGroupName : event.detail.requestParameters.logGroupName;
    try {
        await setRetentionOfCloudwatchLogGroup(logGroupName, 14);
        console.log('Retention has been set to ' + logGroupName + 'for 2 weeks');
        return;
    } catch(error) {
        console.error(error);
        throw error;
    }
};

Error:
Response:
{
  "errorMessage": "Cannot read property 'requestParameters' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "exports.handler (/var/task/index.js:14:81)"
  ]
}

Request ID:
"bc0d27db-1582-4056-9f68-932fea4c9391"

Function Logs:
START RequestId: bc0d27db-1582-4056-9f68-932fea4c9391 Version: $LATEST
2019-07-18T03:48:05.587Z	bc0d27db-1582-4056-9f68-932fea4c9391	{"key1":"value1","key2":"value2","key3":"value3"}
2019-07-18T03:48:05.610Z	bc0d27db-1582-4056-9f68-932fea4c9391	{"errorMessage":"Cannot read property 'requestParameters' of undefined","errorType":"TypeError","stackTrace":["exports.handler (/var/task/index.js:14:81)"]}
END RequestId: bc0d27db-1582-4056-9f68-932fea4c9391
REPORT RequestId: bc0d27db-1582-4056-9f68-932fea4c9391	Duration: 43.63 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 27 MB

**Comment by koladilip** [comment]
Ok, so you are directly executing from Lambda using Test feature?

**Comment by koladilip** [comment]
You need to do using CloudWatch event rule then only it will work.

> Create CloudWatch event rule
> Go to services → CloudWatch → Rules → click on Create rule .
> Event Source → choose Event Pattern → select CloudWatch Logs in Service Name , AWS API Call via CloudTrail in Event Type (If you don’t have Trail setup in CloudTrail, do first. To get help refer this document), CreateLogGroup in Specific operation(s)→ Targets → select Lambda function → select previously created lambda function → click on Configure details .
> Give Name, Description, State should be enabled → click on Create rule .

Refer: https://medium.com/tensult/manage-aws-cloudwatch-log-group-retention-using-automation-26add478b0c5

**Comment by adawg123** [comment]
I am pasting my lambda role and cloud watch rule logic which the rule is enabled and targeting the lambda function I created.

Here is my lambda role:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutRetentionPolicy",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}

Here is CloudWatch rule logic:

**Comment by adawg123** [comment]
> Ok, so you are directly executing from Lambda using Test feature?

Yes

**Comment by sabiram** [comment]
Hi @koladilip @farazamad 

I am getting same error while invoking the lambda function. I followed everything that you have discussed here, but receiving same error. Could you please update me your findings here as I can see the case has been closed before fixing up ?
