### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adawg123** [tensult/aws-automation#26]
Hi,

The lambda below is setting retention for all newly created log groups to 14 whether its set to Never expire or any other value. How can you set this to only trigger when new log group has retention set to Never Expire, if it is a different value say 30 then don't do anything.

const AWS = require('aws-sdk');
const cloudwatchLogs = new AWS.CloudWatchLogs();

function setRetentionOfCloudwatchLogGroup(logGroupName, duration) {
    let params = {
        logGroupName : logGroupName,
        retentionInDays: duration
    };
    return cloudwatchLogs.putRetentionPolicy(params).promise();
}

exports.handler = async (event) => {
    const logGroupName = event.logGroupName ? event.logGroupName : event.detail.requestParameters.logGroupName;
    try {
        await setRetentionOfCloudwatchLogGroup(logGroupName, 14);
        console.log('Retention has been set to ' + logGroupName + 'for 2 weeks');
        return;
    } catch(error) {
        console.error(error);
        throw error;
    }
};

**Comment by adawg123** [comment]
Any help is appreciated please.

**Comment by paragpoddar** [comment]
@adawg123 ,

https://github.com/tensult/aws-automation/blob/refactor-cloudwatch-log-group-retention/set-cloudwatch-log-group-retention/index.js

You can use this script. This will set retention only when new log group has retention set to Never Expire. If already retention set, it won't do anything.

**Comment by adawg123** [comment]
Thank you so much, it worked!

**Comment by adawg123** [comment]
How can this logic be implemented for this script to set retention to existing log groups:
https://github.com/tensult/aws-automation/blob/master/update_cloudwatch_log_group_retention.js

**Comment by koladilip** [comment]
@adawg123 
 set AWS environment variables using: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html then execute following:
 node update_cloudwatch_log_group_retention.js -r <aws-region> -l <logGroupNamePrefix> -R <retention-period-in-days>

**Comment by koladilip** [comment]
Try this and using new -s option.
https://github.com/tensult/aws-automation/blob/master/update_cloudwatch_log_group_retention.js

**Comment by koladilip** [comment]
Git pull and try again.

**Comment by adawg123** [comment]
Thank you @koladilip
